apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Migration Job
#
# The Job expects the namespace and the gaku-secret to exist already

resources:
- ../../../base/db-migration

images:
- name: gaku-migrator
  newName: 100731996173.dkr.ecr.eu-central-1.amazonaws.com/gaku-migrator
  newTag: latest
