apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml
  - postgres/pvc.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml

# For local, all images will be load directly to node's daemon.
# The imagse won't also be uploaded to any registry.
patches:
  - target:
      kind: Deployment|Job
      name: gaku-api|gaku-web|db-migrate
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never

# Name consistent with other envs and cleaner for local.
generatorOptions:
  disableNameSuffixHash: true

# For local, the credentials come from a file on disk.
secretGenerator:
  - name: gaku-secret
    namespace: gaku
    envs:
      - .env.k8s
