apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gaku-ingress
  namespace: gaku
spec:
  rules:
    - host: gaku.local
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: gaku-api
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gaku-web
                port:
                  number: 8080
